#!/bin/bash
#
# Structural checks on a built ISO. These are the invariants that distinguish an
# ISO which merely built from one that can actually boot -- every failure mode
# here has been observed producing a clean, successful build:
#
#   * an initramfs with no archiso hook, which panics with no root filesystem
#   * boot configs naming a kernel or initramfs the ISO does not contain
#   * the wrong architecture's EFI bootloader
#
# Runs against release/*.iso when one exists and skips otherwise, so test/all
# stays fast and VM-free. Pass a specific image as $1 to check that one.

set -euo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)

pass() {
  printf 'ok - %s\n' "$1"
}

fail() {
  local description="$1"
  local detail="${2:-}"

  [[ -n $detail ]] && printf '%s\n' "$detail" >&2
  printf 'not ok - %s\n' "$description" >&2
  exit 1
}

skip() {
  printf 'ok - %s # SKIP %s\n' "$1" "${2:-}"
}

iso="${1:-}"
if [[ -z $iso ]]; then
  iso=$(\ls -t "$ROOT"/release/*.iso 2>/dev/null | head -n1 || true)
fi

if [[ -z $iso || ! -f $iso ]]; then
  skip "iso structure" "no ISO in release/; build one first"
  exit 0
fi

for tool in bsdtar unsquashfs; do
  command -v "$tool" >/dev/null || fail "$tool is required"
done

# The ISO filename carries the architecture archiso built it for.
case "${iso##*/}" in
*aarch64*) arch=aarch64 efi=BOOTAA64.EFI ;;
*x86_64*) arch=x86_64 efi=BOOTX64.EFI ;;
*) fail "cannot determine architecture from ${iso##*/}" ;;
esac

listing=$(bsdtar -tf "$iso" 2>/dev/null) || fail "cannot read $iso as an archive"

has() {
  printf '%s\n' "$listing" | grep -qxF "$1"
}

# --- the ISO is bootable at all -------------------------------------------

file "$iso" | grep -q 'ISO 9660' ||
  fail "$arch: not an ISO 9660 image"
pass "$arch: ISO 9660 image"

has "EFI/BOOT/$efi" ||
  fail "$arch: missing EFI/BOOT/$efi" "$(printf '%s\n' "$listing" | grep -i '\.efi$' || true)"
pass "$arch: EFI/BOOT/$efi present"

# The other architecture's loader must NOT be there: its presence means the
# profile arch and the build arch disagreed somewhere.
case $arch in
aarch64) other=EFI/BOOT/BOOTX64.EFI ;;
*) other=EFI/BOOT/BOOTAA64.EFI ;;
esac
if has "$other"; then
  fail "$arch: unexpected $other in an $arch image"
fi
pass "$arch: no foreign EFI loader"

has "arch/$arch/airootfs.sfs" ||
  fail "$arch: missing arch/$arch/airootfs.sfs"
pass "$arch: squashfs root present"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# --- installer and installed-package compatibility ------------------------
#
# A successful ISO build does not exercise the installer against the package
# scripts embedded in its own live root. limine-mkinitcpio-hook 1.38 replaced
# its pkgbase ownership check with modules.builtin discovery; an installer that
# only knows the old anchor boots normally, installs the whole OS, then fails at
# final bootloader setup. Check the actual pair shipped in the artifact.

bsdtar -xOf "$iso" "arch/$arch/airootfs.sfs" >"$work/airootfs.sfs" 2>/dev/null ||
  fail "$arch: cannot extract live root from image"

installer_impl=$(unsquashfs -cat "$work/airootfs.sfs" \
  usr/share/omarchy-iso/orchestrator/phases_impl.py 2>/dev/null) ||
  fail "$arch: installer implementation missing from live root"

limine_package=$(unsquashfs -ll "$work/airootfs.sfs" 2>/dev/null |
  awk '$NF ~ /\/limine-mkinitcpio-hook-[^/]+\.pkg\.tar\.(zst|xz)$/ {
    package = $NF
  }
  END {
    sub(/^squashfs-root\//, "", package)
    print package
  }')
[[ -n $limine_package ]] ||
  fail "$arch: Limine mkinitcpio package missing from offline mirror"
unsquashfs -cat "$work/airootfs.sfs" "$limine_package" \
  >"$work/limine-mkinitcpio-hook.pkg.tar" 2>/dev/null ||
  fail "$arch: cannot extract Limine mkinitcpio package from live root"
limine_hook=$(bsdtar -xOf "$work/limine-mkinitcpio-hook.pkg.tar" \
  usr/share/libalpm/scripts/limine-mkinitcpio-install 2>/dev/null) ||
  fail "$arch: Limine mkinitcpio hook missing from offline package"

if printf '%s\n' "$limine_hook" | grep -qF 'kernel_dir}/modules.builtin'; then
  printf '%s\n' "$installer_impl" | grep -qF 'modules_builtin_marker' ||
    fail "$arch: installer does not recognize the embedded Limine modules.builtin hook"
elif printf '%s\n' "$limine_hook" | grep -qF 'pacman -Qqo "$pkgbase_file"'; then
  printf '%s\n' "$installer_impl" | grep -qF 'pkgbase_file' ||
    fail "$arch: installer does not recognize the embedded Limine pkgbase hook"
else
  fail "$arch: embedded Limine kernel discovery mechanism is unknown"
fi
pass "$arch: installer recognizes the embedded Limine kernel hook"

# --- boot configs point at files that exist -------------------------------
#
# grub.cfg is generated by substituting %ARCH% and, on aarch64, rewriting the
# kernel filenames. A mismatch here is invisible until the bootloader runs.

grub_cfg=$(bsdtar -xOf "$iso" boot/grub/grub.cfg 2>/dev/null) ||
  fail "$arch: no boot/grub/grub.cfg in image"

referenced=$(printf '%s\n' "$grub_cfg" |
  grep -oE '/arch/boot/[^ ]*(vmlinuz|initramfs)[^ ]*' | sort -u)

[[ -n $referenced ]] ||
  fail "$arch: grub.cfg references no kernel or initramfs"

while read -r path; do
  [[ -n $path ]] || continue
  has "${path#/}" ||
    fail "$arch: grub.cfg references $path, absent from the image" \
      "$(printf '%s\n' "$listing" | grep "^arch/boot/" || true)"
done <<<"$referenced"
pass "$arch: every kernel/initramfs grub.cfg names exists in the image"

# --- device trees and Snapdragon boot arguments ---------------------------
#
# aarch64 only. Qualcomm's UEFI is ACPI-only and Linux has no ACPI support for
# x1e80100, so a Snapdragon X machine boots to a silent black screen without a
# device tree. builder/build-iso.sh stages one into ISO 9660 out of the same
# linux-aarch64 package the live root is pacstrapped from -- but grub.cfg guards
# the entry with -f, so a staging failure is invisible at boot: the menu entry
# simply is not there. Catch it here instead.

dtbs=$(printf '%s\n' "$grub_cfg" |
  grep -oE '^[[:space:]]*devicetree[[:space:]]+[^[:space:]]+' | awk '{print $2}' | sort -u || true)

if [[ $arch == aarch64 ]]; then
  [[ -n $dtbs ]] ||
    fail "aarch64: grub.cfg loads no devicetree; Snapdragon X machines cannot boot this ISO"

  while read -r path; do
    [[ -n $path ]] || continue
    has "${path#/}" ||
      fail "aarch64: grub.cfg loads $path, absent from the image" \
        "$(printf '%s\n' "$listing" | grep '^boot/grub/' || true)"
    # A truncated or zero-length blob passes an existence check and still
    # black-screens. 0xd00dfeed is the flattened-device-tree magic.
    # od -N4 exits after four bytes, so bsdtar takes SIGPIPE; under pipefail
    # that would abort the script rather than report anything.
    magic=$(bsdtar -xOf "$iso" "${path#/}" 2>/dev/null | od -An -tx1 -N4 | tr -d ' ' || true)
    [[ $magic == d00dfeed ]] ||
      fail "aarch64: $path is not a device tree blob (magic $magic, want d00dfeed)"
  done <<<"$dtbs"
  pass "aarch64: every devicetree grub.cfg names is present and is a valid FDT"

  # The device tree alone is not enough: without these the clock and
  # power-domain drivers gate the panel and the USB/PCIe links before their
  # consumers bind, and the machine has no serial port to report it on.
  for required in rd.udev.event_timeout=5 clk_ignore_unused pd_ignore_unused efi=noruntime console=tty0; do
    printf '%s\n' "$grub_cfg" | grep -qF -- "$required" ||
      fail "aarch64: grub.cfg names no '$required'; the Snapdragon entry would not boot"
  done
  pass "aarch64: Snapdragon kernel arguments present"
elif [[ -n $dtbs ]]; then
  fail "x86_64: grub.cfg loads a devicetree, which x86 firmware has no use for"
fi

# --- the live initramfs can actually mount the medium ---------------------
#
# The archiso hook is what finds and mounts airootfs.sfs off the boot medium.
# Without it the kernel boots and panics. This has happened: linux-aarch64 owns
# its own mkinitcpio preset, which builds against /etc/mkinitcpio.conf -- and
# omarchy-settings replaces that file with the *target* system's hooks.

initramfs_path=$(printf '%s\n' "$referenced" | grep 'initramfs' | head -n1)
initramfs_path="${initramfs_path#/}"

if ! command -v lsinitcpio >/dev/null; then
  skip "$arch: initramfs carries the archiso hook" "lsinitcpio not installed"
  exit 0
fi

bsdtar -xOf "$iso" "$initramfs_path" >"$work/initramfs.img" 2>/dev/null ||
  fail "$arch: cannot extract $initramfs_path"

hooks=$(lsinitcpio "$work/initramfs.img" 2>/dev/null | grep -oE 'hooks/[a-z_0-9-]+$' | sed 's|hooks/||' | sort -u)

printf '%s\n' "$hooks" | grep -qx archiso ||
  fail "$arch: initramfs has no archiso hook; this ISO would panic on boot" \
    "hooks present: $(printf '%s' "$hooks" | tr '\n' ' ')"
pass "$arch: initramfs carries the archiso hook"

printf '%s\n' "$hooks" | grep -qx archiso_loop_mnt ||
  fail "$arch: initramfs missing archiso_loop_mnt" \
    "hooks present: $(printf '%s' "$hooks" | tr '\n' ' ')"
pass "$arch: initramfs carries archiso_loop_mnt"
